/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "UTILS.h"
#include "STD_TYPES.h"

#include "RCC_interface.h"
#include "GPIO_interface.h"



void CLOCK_init()
{
	MCAL_RCC_InitSysClock();   //PLL CLOCK SELECTED WITH EXTERNAL CLOCK 16 MHZ
	MCAL_RCC_EnablePeripheral(RCC_APB2,RCC_APB2ENR_IOPBEN);  //ENABLE PORTB
}

void GPIO_init()
{
	MCAL_GPIO_SetPinMode(GPIO_PORTB, GPIO_PIN0, GPIO_OUTPUT_PUSH_PULL_10MHZ);
	MCAL_GPIO_SetPinMode(GPIO_PORTB, GPIO_PIN1, GPIO_OUTPUT_PUSH_PULL_10MHZ);

	MCAL_GPIO_SetPinMode(GPIO_PORTB, GPIO_PIN10, GPIO_INPUT_FLOATING_MOD);
	MCAL_GPIO_SetPinMode(GPIO_PORTB, GPIO_PIN11, GPIO_INPUT_FLOATING_MOD);



}


int main(void)
{
	CLOCK_init();
	GPIO_init();

	while(1){
		u8 VAL10, VAL11;
		MCAL_GPIO_GetPinValue(GPIO_PORTB,GPIO_PIN10,&VAL10);
		MCAL_GPIO_GetPinValue(GPIO_PORTB,GPIO_PIN11,&VAL11);
		if(VAL10 == 1)
		{
			MCAL_GPIO_SetPinValue(GPIO_PORTB,GPIO_PIN0, GPIO_HIGH);
		}
		else{
			MCAL_GPIO_SetPinValue(GPIO_PORTB,GPIO_PIN0, GPIO_LOW);

		}

		if(VAL11 == 0)
		{
			MCAL_GPIO_SetPinValue(GPIO_PORTB,GPIO_PIN1, GPIO_HIGH);
		}
		else{
			MCAL_GPIO_SetPinValue(GPIO_PORTB,GPIO_PIN1, GPIO_LOW);

		}
	}
}
